#!/usr/bin/env python3
"""Regenerate the comparison table + version/date strings in landing/index.html
from docs/compare/aikido-semgrep.md (the maintained source of truth).

Intended as the Cloudflare Pages build command (`python3 landing/build.py`,
output dir `landing`) so every deploy is in sync with the repo state.
Idempotent — safe to run locally too. Exits non-zero (failing the deploy)
if the doc's format drifts from what it can parse.
"""
import html
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "compare" / "aikido-semgrep.md"
PAGE = ROOT / "landing" / "index.html"
START, END = "<!-- compare:start", "<!-- compare:end -->"


def die(msg):
    sys.exit(f"landing/build.py: ERROR — {msg}")


md = DOC.read_text(encoding="utf-8")
page = PAGE.read_text(encoding="utf-8")

# --- header: date + kit version ---
m = re.search(
    r"\*\*Last updated:\*\*\s*([0-9]{4}-[0-9]{2}-[0-9]{2})\s*·\s*kit\s*\*\*v([0-9]+\.[0-9]+\.[0-9]+)\*\*", md
)
if not m:
    die("could not parse '**Last updated:** YYYY-MM-DD · kit **vX.Y.Z**' from the doc header")
doc_date, ver = m.group(1), m.group(2)

# --- parse the feature comparison table ---
try:
    section = md.split("## Feature comparison", 1)[1]
except IndexError:
    die("no '## Feature comparison' section in the doc")

rows = []
started = False
for line in section.splitlines():
    line = line.strip()
    if not line.startswith("|"):
        if started:
            break
        continue
    started = True
    cells = [c.strip() for c in line.strip("|").split("|")]
    if len(cells) != 4:
        die(f"table row does not have 4 columns: {line!r}")
    if cells[0].lower() == "capability" or set(cells[0]) <= {"-", ":"}:
        continue
    rows.append(cells)
if len(rows) < 10:
    die(f"only {len(rows)} data rows parsed — table format changed?")


def clean(s):
    s = re.sub(r"\*\*(.+?)\*\*", r"\1", s)          # bold
    s = re.sub(r"`(.+?)`", r"\1", s)                 # inline code
    s = re.sub(r"\[(.+?)\]\([^)]+\)", r"\1", s)     # links -> text
    s = s.replace("🔜", "→")                         # planned marker, page renders as arrow
    return html.escape(s, quote=False)


# (md prefix, css class, rendered symbol)
MARKS = [("✓", "y", "✓"), ("✗", "n", "✗"), ("Partial", "p", "◐"),
         ("Limited", "p", "◐"), ("🔜", "s", "→"), ("—", "d", "—")]


def cell(raw):
    s = raw.strip()
    if not s:
        return "<td></td>"
    if s.lower() == "unpublished":
        return '<td class="m d">unpublished</td>'
    if s.startswith("MIT"):
        return f'<td class="m y">{clean(s)}</td>'
    for prefix, cls, sym in MARKS:
        if s.startswith(prefix):
            rest = s[len(prefix):].strip(" —-:")
            if rest.startswith("(") and rest.endswith(")"):
                rest = rest[1:-1]
            rest = clean(rest).strip()
            if not rest:
                return f'<td class="m {cls}">{sym}</td>'
            if len(rest) <= 14:
                return f'<td class="m {cls}">{sym} {rest}</td>'
            return f'<td><span class="m {cls}">{sym}</span><span class="note">{rest}</span></td>'
    return f"<td>{clean(s)}</td>"


trs = [f"<tr><td>{clean(r[0])}</td>{cell(r[1])}{cell(r[2])}{cell(r[3])}</tr>" for r in rows]

# --- splice between markers ---
si, ei = page.find(START), page.find(END)
if si == -1 or ei == -1:
    die("compare markers missing in landing/index.html")
line_start = START + " — generated by landing/build.py from docs/compare/aikido-semgrep.md; edits between markers are overwritten -->"
block = "\n".join("          " + tr for tr in trs)
page = page[:si] + line_start + "\n" + block + "\n          " + page[ei:]

# --- version + date strings across the page ---
page = re.sub(r"\bv[0-9]+\.[0-9]+\.[0-9]+\b", f"v{ver}", page)
page = re.sub(r"Last updated [0-9]{4}-[0-9]{2}", f"Last updated {doc_date[:7]}", page)
page = re.sub(r"findings-[0-9]{4}-[0-9]{2}-[0-9]{2}\.md", f"findings-{doc_date}.md", page)

PAGE.write_text(page, encoding="utf-8")
print(f"landing/build.py: OK — {len(trs)} rows · kit v{ver} · doc date {doc_date}")
